#pragma once
// Standby B1 LED: mode 0 = fixed brightness, 1 = breathing. B2 is skip.
// Period is one complete fade-in/fade-out cycle (500..5000 ms).
#define BOARD_B1_IDLE_LED_MODE 0
#define BOARD_B1_IDLE_LED_PERIOD_MS 2000
#define BOARD_B1_IDLE_LED_BRIGHTNESS 0
#define BOARD_CEC_DEFAULT_VOLUME 20
#define BOARD_CEC_VOLUME_TOLERANCE 2
#define BOARD_CEC_VOLUME_RESET_DELAY_MS 30000
#define BOARD_HDMI_DETECT_DEBOUNCE_MS 100
#define BOARD_ARC_COUNT 1
#define BOARD_BUTTON_COUNT 4
#define BOARD_UART_TX 0
#define BOARD_UART_RX 1
#define BOARD_SD_SCK 2
#define BOARD_SD_MOSI 3
#define BOARD_SD_MISO 4
#define BOARD_SD_CS 5
#define BOARD_STATUS_LED 25
#define BOARD_HPD 18
#define BOARD_ARC1_TX 16
#define BOARD_ARC1_CEC 19
#define BOARD_ARC1_DETECT 17
#define BOARD_ARC1_SDA 6
#define BOARD_ARC1_SCL 7
#define BOARD_ARC1_LED 15
#define BOARD_KEY_PINS {10, 13, 21, 27}
#define BOARD_LED_PINS {9, 12, 20, 26}
#define BOARD_LED_N_PINS {11, 14, 22, 28}
#define BOARD_CONTROL_PINS 9,10,11,12,13,14,20,21,22,26,27,28
#define BOARD_NEXT_KEY 1
#define BOARD_VOLUME_UP_KEY 2
#define BOARD_VOLUME_DOWN_KEY 3
