set(PICODAC_BOARD "c1" CACHE STRING "Application board: c1 or c2")
set_property(CACHE PICODAC_BOARD PROPERTY STRINGS c1 c2)
if(NOT PICODAC_BOARD MATCHES "^(c1|c2)$")
    message(FATAL_ERROR "PICODAC_BOARD must be c1 or c2")
endif()
# Headers are the single source of truth for firmware and configuration checks.
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/${PICODAC_BOARD}.h")
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/${PICODAC_BOARD}.h" board_definitions
     REGEX "^#define BOARD_[A-Z0-9_]+ [0-9,]+$")
foreach(definition IN LISTS board_definitions)
    string(REGEX REPLACE "^#define ([A-Z0-9_]+) (.*)$" "\\1;\\2" fields "${definition}")
    list(GET fields 0 name)
    list(GET fields 1 value)
    string(REPLACE "," ";" value "${value}")
    set(${name} ${value})
endforeach()
set(PICODAC_SPDIF_PIN ${BOARD_ARC1_TX})
set(PICODAC_CEC_PIN ${BOARD_ARC1_CEC})
set(PICODAC_SD_SCK_PIN ${BOARD_SD_SCK})
set(PICODAC_SD_MOSI_PIN ${BOARD_SD_MOSI})
set(PICODAC_SD_MISO_PIN ${BOARD_SD_MISO})
set(PICODAC_SD_CS_PIN ${BOARD_SD_CS})
message(STATUS "PICODAC board: ${PICODAC_BOARD}, ARC ports: ${BOARD_ARC_COUNT}")
